### ISSUE TITLE
Can't run hoc on SVN checked out repo (win 8.1 x64)

### ISSUE THREAD

**Issue by kbhavik** [teamed/hoc#13]
i installed ruby, gems, ruby dev kit on win 8.1 X64. I installed hoc via CMD and it was successful. I checked out SVN repo and opened cmd and went to checked out repo directory and ran hoc. I get this error please help and let me know how you generate graph.

```
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/hoc-0.6/lib/hoc/svn.rb:39:in ``': No such file or directory - diffstat -V (Errno::ENOENT)

from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/hoc-0.6/lib/hoc/svn.rb:39:in `hits'

from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/hoc-0.6/lib/hoc.rb:54:in `report'

from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/hoc-0.6/bin/hoc:61:in `'

from C:/Ruby22-x64/bin/hoc:23:in `load'

from C:/Ruby22-x64/bin/hoc:23:in `
```

**Comment by kbhavik** [comment]
![hoc_issue](https://cloud.githubusercontent.com/assets/14030339/11989731/23a269e8-aa29-11e5-8b16-978861012bde.JPG)
I'm facing issues with both svn and git repo, while running HoC. help!!!!

**Comment by yegor256** [comment]
@kbhavik sorry for delay. I never tested it on Windows. Let me try...

**Comment by kbhavik** [comment]
@yegor256 Thanks for looking into it. I was asked by Boss to create reports for new lines of code per project. While browsing i came across your blog about HoC and I planned to represent my reports with HoC. However it's not working although I also used svn2git for conversion of few SVN repos to GiT. I will really appreciate if you could help me out with HoC and guide me how to generate reports/Graphs using HoC. If possible representing authors who contribute or edited the code.

**Comment by yegor256** [comment]
@kbhavik I will try to make it working on Windows, but I'm not sure I will succeed. Give me a few hours...

**Comment by kbhavik** [comment]
@yegor256 Take your time. I hope it works.

**Comment by yegor256** [comment]
@kbhavik I managed to reproduce this problem in integration test: https://ci.appveyor.com/project/yegor256/hoc/build/52 Will try to fix or document it now

**Comment by yegor256** [comment]
@rultor release, tag is `0.7`

**Comment by yegor256** [comment]
@kbhavik try version 0.7. It will work without problems with Git repository. For SVN repository you will have to install diffstat, see: http://sourceforge.net/projects/mingw/files/MSYS/Extension/diffstat/

**Comment by yegor256** [comment]
@rultor release, tag is `0.7`

**Comment by kbhavik** [comment]
Hey! HoC on git is working. I installed diffstat using MinGW installer but on svn repo i get this error:

![zzz](https://cloud.githubusercontent.com/assets/14030339/11997471/8bafff86-aaa2-11e5-92a4-06aee7738516.JPG)

**Comment by kbhavik** [comment]
@yegor256 more issue on svn:

![zzz](https://cloud.githubusercontent.com/assets/14030339/11997556/c9755fc6-aaa4-11e5-962b-cffe88e9a964.JPG)

**Comment by yegor256** [comment]
@kbhavik I managed to reproduce the problem in https://ci.appveyor.com/project/yegor256/hoc/build/61 Will try to fix it now

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.1`

**Comment by yegor256** [comment]
@kbhavik try version 0.7.1, I believe it will work without problems, with SVN

**Comment by kbhavik** [comment]
@yegor256 Thank you for modifying the code and taking pains to resolve the issue just for a single guy! It's working now.. Hats off to you.. Can you please tell me how to generate a graph to show loc and hoc by every author. Like you represented in your blog.

![image](https://cloud.githubusercontent.com/assets/14030339/12005633/0b212d42-abd6-11e5-8914-9fc4e92bf830.png)

**Comment by kbhavik** [comment]
@yegor256 Kindly advice..

**Comment by yegor256** [comment]
@kbhavik hm.. that's a good question. I built this graph manually, collecting data not via this `hoc` Ruby gem, but directly from Git. It wasn't easy :) I wrote a small software just to build this small graph for the blog post.

**Comment by yegor256** [comment]
@kbhavik can you please close this ticket, if everything works as you expected. And thanks for using this tool :)

**Comment by kbhavik** [comment]
Thanks for helping!
